id: P2B534B69
initial_creation_type: input
source_metadata:
  title: Nonsectarianism Series
  language: es
  description: 'Texts on the theme of nonsectarianism, impartiality or the absence
    of sectarian bias, a central ideal of the so-called nonsectarian or rimé (ris
    med) movement that blossomed in nineteenth-century Kham:'
  volume:
    24202e956f24457e829ae31e5798ba4e:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    d38c5c9d1c374b58b1c362760026ccc4:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    b6d1eb54208446d48dae3d3ff0d946ce:
      title: A Sun to Banish the Darkness of Wrong Views
      parent: Advice
    8aeaa2de67a541c59dd10a7624e7382c:
      title: 'Opening the Door of Dharma: A Brief Discourse on the Essence of All
        Vehicles'
      parent: Advice
    eee890e6b9c34594b26237fd6bc2a09f:
      title: Satirical Advice for the Four Schools
      parent: Advice
    c0e6ea834abd4979a8f3418b4f764b0f:
      title: The Four Dharma Traditions of Tibet
      parent: Advice
    4520bcb49ffe41b980ae043c2a37ae0d:
      title: 'The Sage''s Harmonious Song of Truth: A Prayer for the Flourishing of
        the Non-Sectarian Teachings of the Buddha'
      parent: Aspiration Prayers
    c5540bf412c448d2bdebce5ad27a793a:
      title: 'All-Pervading Auspiciousness: An Aspiration for the Spread of the Teachings
        of the Eight Great Chariots of the Practice Lineage'
      parent: Aspiration Prayers
    2ed29b82d6f246a8b0a0445cda034ef1:
      title: Aspiration for the Spread of the Teachings
      parent: Aspiration Prayers
    223374a8363247d5bc526ec6e4436793:
      title: 'The Swift Fulfilment of Wishes: A Prayer of Aspiration'
      parent: Aspiration Prayers
    26a29e6181244f24a3e1fa57207349a8:
      title: Aspiration for the Spread of the Teachings of the Eight Chariots of the
        Practice Lineage
      parent: Aspiration Prayers
    b0e89b6d981144d5905a02560e75b91c:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    f7d0573ee4574923962e63aa67e5aa68:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Prayers
    f2fc9c0fe14f4764af8e0b65fcfbe7f4:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    c8c24dcbbf124b1c8ed9218c30c8c8d1:
      title: 'The Treasury of Blessings: A Prayer to Recall the Sublime Masters who
        Showed Great Kindness to the Land of Snows'
      parent: Prayers
    e8f828975a2d4e198b958eddf4274f02:
      title: 'The Flower of Faith: A Prayer to the Twenty-Five Founders of Buddha''s
        Teachings in Tibet'
      parent: Prayers
    82ac0cce624f4857bfe7f94d91db4d19:
      title: 'The Seed of Faith: A Prayer to the Sublime Ones'
      parent: Prayers
    93e4dd8df5df473986f32ce6970da269:
      title: Upon Hearing the Fluted Speech of Kunzang Dechen Tsomo, Queen Mother
        of Sikkim
      parent: Songs
created_at: '2022-03-01T04:51:37.222605'
last_modified_at: '2022-03-01T04:51:37.222608'
